"Enable Client" = true

[Client]
	#Changes to sounds and music. Disabling this feature requires a Minecraft restart.
	"Enable Sounds & Music" = true
	#Misc client side changes
	"Enable Misc" = true
	#Changes to light
	"Enable Light" = true
	#Makes fog less invasive in some contexts
	"Enable Fog" = true

	#Changes to sounds and music. Disabling this feature requires a Minecraft restart.
	[Client."Sounds & Music"]
		#Multiplies the time it takes for music to play by this value (in vanilla, normal music plays each 10 to 20 minutes).
		#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
		"Music delay multiplier" = 0.1

	#Misc client side changes
	[Client.Misc]
		#Multiplies the world border transparency by this value
		#Range: 0.0 ~ 1.0
		"World Border Transparency" = 0.4
		#If true, the world border height is reduced by 4 times.
		"Shorter world border" = true
		#Set the max height of the world border.
		#Range: 1.0 ~ 1.7976931348623157E308
		"Cap world border height" = 128.0
		#If true, camera will not tilt when taking magic, wither, on fire, cramming, drowning and thorns damage.
		"No tilting with some damage types" = true
		#If true, the outline around blocks will be red if the tool in hand will make drops not ... drop.
		"Red block outline with wrong tool" = true

	#Changes to light
	[Client.Light]
		#If true night vision will no longer flash 10 seconds before expiring, instead will slowly fade out 2 seconds before expiring.
		"No Night Vision Flashing" = true
		#If enabled, the brightness will be set to at most 15% regardless of the current brightness in video settings.
		"Force darkness" = true

	#Makes fog less invasive in some contexts
	[Client.Fog]
		#If true you'll be able to see better in lava when with the Fire Resistance Effect.
		"Better visibility in Lava with Fire Resistance Lava" = true
		#If true Nether Fog is no longer limited to 12 chunks.
		"Better Nether Fog" = true
		#Render distance is multiplied by this value in the Nether. Vanilla is 0.5.
		#Range: 0.0 ~ 1.0
		"Nether Fog Ratio" = 0.75
		#Changes fog to start closer to the player. E.g. A value of 0.5 makes fog start at half the render distance. Vanilla is 1, Pre-1.18.1 was 0.75, Pre-1.7.2 was 0.25
		#Range: 0.0 ~ 1.0
		"Overworld Fog Start Ratio" = 0.4
		#Changes fog ratio when raining
		#Range: 0.0 ~ 1.0
		"Overworld Fog Start Ratio on Rain" = 0.0

