let activeNpcBlocks = new Set();

let npcSpawnBlocks = [
  "minecraft:crafting_table",
  "doggytalents:dog_bed",
  "irons_spellbooks:alchemist_cauldron",
  "drinkbeer:bartending_table_normal",
  "minecraft:red_bed",
  "numismatic-overhaul:shop",
  "cataclysm:mechanical_fusion_anvil",
  "minecraft:flower_pot",
  "quark:gunpowder_sack",
  "aquaculture:tackle_box",
  "sophisticatedstorage:decoration_table",
];

let NPC_COMMANDS = {
  "minecraft:crafting_table":
    "easy_npc preset import data prodigiumreforged:preset/terraria/guide.npc.nbt ~ ~ ~",
  "drinkbeer:bartending_table_normal":
    "easy_npc preset import data prodigiumreforged:preset/terraria/tavernkeep.npc.nbt ~ ~ ~",
  "doggytalents:dog_bed":
    "easy_npc preset import data prodigiumreforged:preset/terraria/zoologist.npc.nbt ~ ~ ~",
  "irons_spellbooks:alchemist_cauldron":
    "easy_npc preset import data prodigiumreforged:preset/terraria/wizard.npc.nbt ~ ~ ~",
  "minecraft:red_bed":
    "easy_npc preset import data prodigiumreforged:preset/terraria/nurse.npc.nbt ~ ~ ~",
  "numismatic-overhaul:shop":
    "easy_npc preset import data prodigiumreforged:preset/terraria/merchant.npc.nbt ~ ~ ~",
  "cataclysm:mechanical_fusion_anvil":
    "easy_npc preset import data prodigiumreforged:preset/terraria/goblin.npc.nbt ~ ~ ~",
  "minecraft:flower_pot":
    "easy_npc preset import data prodigiumreforged:preset/terraria/dryad.npc.nbt ~ ~ ~",
  "quark:gunpowder_sack":
    "easy_npc preset import data prodigiumreforged:preset/terraria/arms_dealer.npc.nbt ~ ~ ~",
  "aquaculture:tackle_box":
    "easy_npc preset import data prodigiumreforged:preset/terraria/angler.npc.nbt ~ ~ ~",
  "sophisticatedstorage:decoration_table":
    "easy_npc preset import data prodigiumreforged:preset/terraria/steampunker.npc.nbt ~ ~ ~",
};

let NPC_HOME_COMMANDS = {
  "minecraft:crafting_table":
    "easy_npc navigation set home 3bd2ab72-41d7-4472-a480-5d849f76298c ~ ~ ~",
  "drinkbeer:bartending_table_normal":
    "easy_npc navigation set home 407a8d48-2853-486f-85e0-b6a6abc04f63 ~ ~ ~",
  "doggytalents:dog_bed":
    "easy_npc navigation set home 3d380f27-8f30-4daa-aaf1-f720c34afb86 ~ ~ ~",
  "irons_spellbooks:alchemist_cauldron":
    "easy_npc navigation set home f5be7dde-967f-4b27-8b50-7e6a9ddb35ce ~ ~ ~",
  "minecraft:red_bed":
    "easy_npc navigation set home 88f7ac3f-9696-4c5b-bf4a-52e3b40e10ac ~ ~ ~",
  "numismatic-overhaul:shop":
    "easy_npc navigation set home 2d146e4f-6905-49b4-9163-62a5d5fb73f3 ~ ~ ~",
  "cataclysm:mechanical_fusion_anvil":
    "easy_npc navigation set home bc6503ee-44cf-42a9-a6fa-6a0f3d82af73 ~ ~ ~",
  "minecraft:flower_pot":
    "easy_npc navigation set home 31d2de80-97a0-41cf-a227-11ff3e097e25 ~ ~ ~",
  "quark:gunpowder_sack":
    "easy_npc navigation set home d4ef3e8d-ccc8-4ac5-a7e2-5199a0e27ecf ~ ~ ~",
  "aquaculture:tackle_box":
    "easy_npc navigation set home 9c3463c4-9010-4733-a594-260f391449cc ~ ~ ~",
  "sophisticatedstorage:decoration_table":
    "easy_npc navigation set home 497c50ac-c667-4c70-a784-a1e3f07f35c5 ~ ~ ~",
};

let NPC_QUEST_COMMANDS = {
  "minecraft:crafting_table":
    "ftbquests change_progress @p complete 384F487E612876CC",
  "drinkbeer:bartending_table_normal":
    "ftbquests change_progress @p complete 6F79F027D77C3DAD",
  "doggytalents:dog_bed":
    "ftbquests change_progress @p complete 70ABE0C1C74091F0",
  "irons_spellbooks:alchemist_cauldron":
    "ftbquests change_progress @p complete 47E990C188715ECC",
  "minecraft:red_bed": "ftbquests change_progress @p complete 17977EFFC2672EBA",
  "numismatic-overhaul:shop":
    "ftbquests change_progress @p complete 59E9072E7D9FCB02",
  "cataclysm:mechanical_fusion_anvil":
    "ftbquests change_progress @p complete 57002871DA02FC72",
  "minecraft:flower_pot":
    "ftbquests change_progress @p complete 4F808E1A98977B6C",
  "quark:gunpowder_sack":
    "ftbquests change_progress @p complete 1775200C7A70CD7E",
  "aquaculture:tackle_box":
    "ftbquests change_progress @p complete 6EED8FB36CADB75B",
  "sophisticatedstorage:decoration_table":
    "ftbquests change_progress @p complete 40FF13E4F5C0D544",
};

let categoryBlocks = {
  chairs: [
    "valhelsia_furniture:oak_chair",
    "valhelsia_furniture:spruce_chair",
    "valhelsia_furniture:birch_chair",
    "valhelsia_furniture:jungle_chair",
    "valhelsia_furniture:acacia_chair",
    "valhelsia_furniture:cherry_chair",
    "valhelsia_furniture:dark_oak_chair",
    "valhelsia_furniture:mangrove_chair",
    "valhelsia_furniture:crimson_chair",
    "valhelsia_furniture:warped_chair",
    "valhelsia_furniture:hay_oak_chair",
    "valhelsia_furniture:hay_spruce_chair",
    "valhelsia_furniture:hay_birch_chair",
    "valhelsia_furniture:hay_jungle_chair",
    "valhelsia_furniture:hay_acacia_chair",
    "valhelsia_furniture:hay_cherry_chair",
    "valhelsia_furniture:hay_dark_oak_chair",
    "valhelsia_furniture:hay_mangrove_chair",
    "valhelsia_furniture:hay_crimson_chair",
    "valhelsia_furniture:hay_warped_chair",
    "valhelsia_furniture:white_oak_chair",
    "valhelsia_furniture:orange_oak_chair",
    "valhelsia_furniture:magenta_oak_chair",
    "valhelsia_furniture:light_blue_oak_chair",
    "valhelsia_furniture:yellow_oak_chair",
    "valhelsia_furniture:lime_oak_chair",
    "valhelsia_furniture:pink_oak_chair",
    "valhelsia_furniture:gray_oak_chair",
    "valhelsia_furniture:light_gray_oak_chair",
    "valhelsia_furniture:cyan_oak_chair",
    "valhelsia_furniture:purple_oak_chair",
    "valhelsia_furniture:blue_oak_chair",
    "valhelsia_furniture:brown_oak_chair",
    "valhelsia_furniture:green_oak_chair",
    "valhelsia_furniture:red_oak_chair",
    "valhelsia_furniture:black_oak_chair",
    "valhelsia_furniture:white_spruce_chair",
    "valhelsia_furniture:orange_spruce_chair",
    "valhelsia_furniture:magenta_spruce_chair",
    "valhelsia_furniture:light_blue_spruce_chair",
    "valhelsia_furniture:yellow_spruce_chair",
    "valhelsia_furniture:lime_spruce_chair",
    "valhelsia_furniture:pink_spruce_chair",
    "valhelsia_furniture:gray_spruce_chair",
    "valhelsia_furniture:light_gray_spruce_chair",
    "valhelsia_furniture:cyan_spruce_chair",
    "valhelsia_furniture:purple_spruce_chair",
    "valhelsia_furniture:blue_spruce_chair",
    "valhelsia_furniture:brown_spruce_chair",
    "valhelsia_furniture:green_spruce_chair",
    "valhelsia_furniture:red_spruce_chair",
    "valhelsia_furniture:black_spruce_chair",
    "valhelsia_furniture:white_birch_chair",
    "valhelsia_furniture:orange_birch_chair",
    "valhelsia_furniture:magenta_birch_chair",
    "valhelsia_furniture:light_blue_birch_chair",
    "valhelsia_furniture:yellow_birch_chair",
    "valhelsia_furniture:lime_birch_chair",
    "valhelsia_furniture:pink_birch_chair",
    "valhelsia_furniture:gray_birch_chair",
    "valhelsia_furniture:light_gray_birch_chair",
    "valhelsia_furniture:cyan_birch_chair",
    "valhelsia_furniture:purple_birch_chair",
    "valhelsia_furniture:blue_birch_chair",
    "valhelsia_furniture:brown_birch_chair",
    "valhelsia_furniture:green_birch_chair",
    "valhelsia_furniture:red_birch_chair",
    "valhelsia_furniture:black_birch_chair",
    "valhelsia_furniture:white_jungle_chair",
    "valhelsia_furniture:orange_jungle_chair",
    "valhelsia_furniture:magenta_jungle_chair",
    "valhelsia_furniture:light_blue_jungle_chair",
    "valhelsia_furniture:yellow_jungle_chair",
    "valhelsia_furniture:lime_jungle_chair",
    "valhelsia_furniture:pink_jungle_chair",
    "valhelsia_furniture:gray_jungle_chair",
    "valhelsia_furniture:light_gray_jungle_chair",
    "valhelsia_furniture:cyan_jungle_chair",
    "valhelsia_furniture:purple_jungle_chair",
    "valhelsia_furniture:blue_jungle_chair",
    "valhelsia_furniture:brown_jungle_chair",
    "valhelsia_furniture:green_jungle_chair",
    "valhelsia_furniture:red_jungle_chair",
    "valhelsia_furniture:black_jungle_chair",
    "valhelsia_furniture:white_acacia_chair",
    "valhelsia_furniture:orange_acacia_chair",
    "valhelsia_furniture:magenta_acacia_chair",
    "valhelsia_furniture:light_blue_acacia_chair",
    "valhelsia_furniture:yellow_acacia_chair",
    "valhelsia_furniture:lime_acacia_chair",
    "valhelsia_furniture:pink_acacia_chair",
    "valhelsia_furniture:gray_acacia_chair",
    "valhelsia_furniture:light_gray_acacia_chair",
    "valhelsia_furniture:cyan_acacia_chair",
    "valhelsia_furniture:purple_acacia_chair",
    "valhelsia_furniture:blue_acacia_chair",
    "valhelsia_furniture:brown_acacia_chair",
    "valhelsia_furniture:green_acacia_chair",
    "valhelsia_furniture:red_acacia_chair",
    "valhelsia_furniture:black_acacia_chair",
    "valhelsia_furniture:white_cherry_chair",
    "valhelsia_furniture:orange_cherry_chair",
    "valhelsia_furniture:magenta_cherry_chair",
    "valhelsia_furniture:light_blue_cherry_chair",
    "valhelsia_furniture:yellow_cherry_chair",
    "valhelsia_furniture:lime_cherry_chair",
    "valhelsia_furniture:pink_cherry_chair",
    "valhelsia_furniture:gray_cherry_chair",
    "valhelsia_furniture:light_gray_cherry_chair",
    "valhelsia_furniture:cyan_cherry_chair",
    "valhelsia_furniture:purple_cherry_chair",
    "valhelsia_furniture:blue_cherry_chair",
    "valhelsia_furniture:brown_cherry_chair",
    "valhelsia_furniture:green_cherry_chair",
    "valhelsia_furniture:red_cherry_chair",
    "valhelsia_furniture:black_cherry_chair",
    "valhelsia_furniture:white_dark_oak_chair",
    "valhelsia_furniture:orange_dark_oak_chair",
    "valhelsia_furniture:magenta_dark_oak_chair",
    "valhelsia_furniture:light_blue_dark_oak_chair",
    "valhelsia_furniture:yellow_dark_oak_chair",
    "valhelsia_furniture:lime_dark_oak_chair",
    "valhelsia_furniture:pink_dark_oak_chair",
    "valhelsia_furniture:gray_dark_oak_chair",
    "valhelsia_furniture:light_gray_dark_oak_chair",
    "valhelsia_furniture:cyan_dark_oak_chair",
    "valhelsia_furniture:purple_dark_oak_chair",
    "valhelsia_furniture:blue_dark_oak_chair",
    "valhelsia_furniture:brown_dark_oak_chair",
    "valhelsia_furniture:green_dark_oak_chair",
    "valhelsia_furniture:red_dark_oak_chair",
    "valhelsia_furniture:black_dark_oak_chair",
    "valhelsia_furniture:white_mangrove_chair",
    "valhelsia_furniture:orange_mangrove_chair",
    "valhelsia_furniture:magenta_mangrove_chair",
    "valhelsia_furniture:light_blue_mangrove_chair",
    "valhelsia_furniture:yellow_mangrove_chair",
    "valhelsia_furniture:lime_mangrove_chair",
    "valhelsia_furniture:pink_mangrove_chair",
    "valhelsia_furniture:gray_mangrove_chair",
    "valhelsia_furniture:light_gray_mangrove_chair",
    "valhelsia_furniture:cyan_mangrove_chair",
    "valhelsia_furniture:purple_mangrove_chair",
    "valhelsia_furniture:blue_mangrove_chair",
    "valhelsia_furniture:brown_mangrove_chair",
    "valhelsia_furniture:green_mangrove_chair",
    "valhelsia_furniture:red_mangrove_chair",
    "valhelsia_furniture:black_mangrove_chair",
    "valhelsia_furniture:white_crimson_chair",
    "valhelsia_furniture:orange_crimson_chair",
    "valhelsia_furniture:magenta_crimson_chair",
    "valhelsia_furniture:light_blue_crimson_chair",
    "valhelsia_furniture:yellow_crimson_chair",
    "valhelsia_furniture:lime_crimson_chair",
    "valhelsia_furniture:pink_crimson_chair",
    "valhelsia_furniture:gray_crimson_chair",
    "valhelsia_furniture:light_gray_crimson_chair",
    "valhelsia_furniture:cyan_crimson_chair",
    "valhelsia_furniture:purple_crimson_chair",
    "valhelsia_furniture:blue_crimson_chair",
    "valhelsia_furniture:brown_crimson_chair",
    "valhelsia_furniture:green_crimson_chair",
    "valhelsia_furniture:red_crimson_chair",
    "valhelsia_furniture:black_crimson_chair",
    "valhelsia_furniture:white_warped_chair",
    "valhelsia_furniture:orange_warped_chair",
    "valhelsia_furniture:magenta_warped_chair",
    "valhelsia_furniture:light_blue_warped_chair",
    "valhelsia_furniture:yellow_warped_chair",
    "valhelsia_furniture:lime_warped_chair",
    "valhelsia_furniture:pink_warped_chair",
    "valhelsia_furniture:gray_warped_chair",
    "valhelsia_furniture:light_gray_warped_chair",
    "valhelsia_furniture:cyan_warped_chair",
    "valhelsia_furniture:purple_warped_chair",
    "valhelsia_furniture:blue_warped_chair",
    "valhelsia_furniture:brown_warped_chair",
    "valhelsia_furniture:green_warped_chair",
    "valhelsia_furniture:red_warped_chair",
    "valhelsia_furniture:black_warped_chair",
    "valhelsia_furniture:white_upholstered_oak_chair",
    "valhelsia_furniture:orange_upholstered_oak_chair",
    "valhelsia_furniture:magenta_upholstered_oak_chair",
    "valhelsia_furniture:light_blue_upholstered_oak_chair",
    "valhelsia_furniture:yellow_upholstered_oak_chair",
    "valhelsia_furniture:lime_upholstered_oak_chair",
    "valhelsia_furniture:pink_upholstered_oak_chair",
    "valhelsia_furniture:gray_upholstered_oak_chair",
    "valhelsia_furniture:light_gray_upholstered_oak_chair",
    "valhelsia_furniture:cyan_upholstered_oak_chair",
    "valhelsia_furniture:purple_upholstered_oak_chair",
    "valhelsia_furniture:blue_upholstered_oak_chair",
    "valhelsia_furniture:brown_upholstered_oak_chair",
    "valhelsia_furniture:green_upholstered_oak_chair",
    "valhelsia_furniture:red_upholstered_oak_chair",
    "valhelsia_furniture:black_upholstered_oak_chair",
    "valhelsia_furniture:white_upholstered_spruce_chair",
    "valhelsia_furniture:orange_upholstered_spruce_chair",
    "valhelsia_furniture:magenta_upholstered_spruce_chair",
    "valhelsia_furniture:light_blue_upholstered_spruce_chair",
    "valhelsia_furniture:yellow_upholstered_spruce_chair",
    "valhelsia_furniture:lime_upholstered_spruce_chair",
    "valhelsia_furniture:pink_upholstered_spruce_chair",
    "valhelsia_furniture:gray_upholstered_spruce_chair",
    "valhelsia_furniture:light_gray_upholstered_spruce_chair",
    "valhelsia_furniture:cyan_upholstered_spruce_chair",
    "valhelsia_furniture:purple_upholstered_spruce_chair",
    "valhelsia_furniture:blue_upholstered_spruce_chair",
    "valhelsia_furniture:brown_upholstered_spruce_chair",
    "valhelsia_furniture:green_upholstered_spruce_chair",
    "valhelsia_furniture:red_upholstered_spruce_chair",
    "valhelsia_furniture:black_upholstered_spruce_chair",
    "valhelsia_furniture:white_upholstered_birch_chair",
    "valhelsia_furniture:orange_upholstered_birch_chair",
    "valhelsia_furniture:magenta_upholstered_birch_chair",
    "valhelsia_furniture:light_blue_upholstered_birch_chair",
    "valhelsia_furniture:yellow_upholstered_birch_chair",
    "valhelsia_furniture:lime_upholstered_birch_chair",
    "valhelsia_furniture:pink_upholstered_birch_chair",
    "valhelsia_furniture:gray_upholstered_birch_chair",
    "valhelsia_furniture:light_gray_upholstered_birch_chair",
    "valhelsia_furniture:cyan_upholstered_birch_chair",
    "valhelsia_furniture:purple_upholstered_birch_chair",
    "valhelsia_furniture:blue_upholstered_birch_chair",
    "valhelsia_furniture:brown_upholstered_birch_chair",
    "valhelsia_furniture:green_upholstered_birch_chair",
    "valhelsia_furniture:red_upholstered_birch_chair",
    "valhelsia_furniture:black_upholstered_birch_chair",
    "valhelsia_furniture:white_upholstered_jungle_chair",
    "valhelsia_furniture:orange_upholstered_jungle_chair",
    "valhelsia_furniture:magenta_upholstered_jungle_chair",
    "valhelsia_furniture:light_blue_upholstered_jungle_chair",
    "valhelsia_furniture:yellow_upholstered_jungle_chair",
    "valhelsia_furniture:lime_upholstered_jungle_chair",
    "valhelsia_furniture:pink_upholstered_jungle_chair",
    "valhelsia_furniture:gray_upholstered_jungle_chair",
    "valhelsia_furniture:light_gray_upholstered_jungle_chair",
    "valhelsia_furniture:cyan_upholstered_jungle_chair",
    "valhelsia_furniture:purple_upholstered_jungle_chair",
    "valhelsia_furniture:blue_upholstered_jungle_chair",
    "valhelsia_furniture:brown_upholstered_jungle_chair",
    "valhelsia_furniture:green_upholstered_jungle_chair",
    "valhelsia_furniture:red_upholstered_jungle_chair",
    "valhelsia_furniture:black_upholstered_jungle_chair",
    "valhelsia_furniture:white_upholstered_acacia_chair",
    "valhelsia_furniture:orange_upholstered_acacia_chair",
    "valhelsia_furniture:magenta_upholstered_acacia_chair",
    "valhelsia_furniture:light_blue_upholstered_acacia_chair",
    "valhelsia_furniture:yellow_upholstered_acacia_chair",
    "valhelsia_furniture:lime_upholstered_acacia_chair",
    "valhelsia_furniture:pink_upholstered_acacia_chair",
    "valhelsia_furniture:gray_upholstered_acacia_chair",
    "valhelsia_furniture:light_gray_upholstered_acacia_chair",
    "valhelsia_furniture:cyan_upholstered_acacia_chair",
    "valhelsia_furniture:purple_upholstered_acacia_chair",
    "valhelsia_furniture:blue_upholstered_acacia_chair",
    "valhelsia_furniture:brown_upholstered_acacia_chair",
    "valhelsia_furniture:green_upholstered_acacia_chair",
    "valhelsia_furniture:red_upholstered_acacia_chair",
    "valhelsia_furniture:black_upholstered_acacia_chair",
    "valhelsia_furniture:white_upholstered_cherry_chair",
    "valhelsia_furniture:orange_upholstered_cherry_chair",
    "valhelsia_furniture:magenta_upholstered_cherry_chair",
    "valhelsia_furniture:light_blue_upholstered_cherry_chair",
    "valhelsia_furniture:yellow_upholstered_cherry_chair",
    "valhelsia_furniture:lime_upholstered_cherry_chair",
    "valhelsia_furniture:pink_upholstered_cherry_chair",
    "valhelsia_furniture:gray_upholstered_cherry_chair",
    "valhelsia_furniture:light_gray_upholstered_cherry_chair",
    "valhelsia_furniture:cyan_upholstered_cherry_chair",
    "valhelsia_furniture:purple_upholstered_cherry_chair",
    "valhelsia_furniture:blue_upholstered_cherry_chair",
    "valhelsia_furniture:brown_upholstered_cherry_chair",
    "valhelsia_furniture:green_upholstered_cherry_chair",
    "valhelsia_furniture:red_upholstered_cherry_chair",
    "valhelsia_furniture:black_upholstered_cherry_chair",
    "valhelsia_furniture:white_upholstered_dark_oak_chair",
    "valhelsia_furniture:orange_upholstered_dark_oak_chair",
    "valhelsia_furniture:magenta_upholstered_dark_oak_chair",
    "valhelsia_furniture:light_blue_upholstered_dark_oak_chair",
    "valhelsia_furniture:yellow_upholstered_dark_oak_chair",
    "valhelsia_furniture:lime_upholstered_dark_oak_chair",
    "valhelsia_furniture:pink_upholstered_dark_oak_chair",
    "valhelsia_furniture:gray_upholstered_dark_oak_chair",
    "valhelsia_furniture:light_gray_upholstered_dark_oak_chair",
    "valhelsia_furniture:cyan_upholstered_dark_oak_chair",
    "valhelsia_furniture:purple_upholstered_dark_oak_chair",
    "valhelsia_furniture:blue_upholstered_dark_oak_chair",
    "valhelsia_furniture:brown_upholstered_dark_oak_chair",
    "valhelsia_furniture:green_upholstered_dark_oak_chair",
    "valhelsia_furniture:red_upholstered_dark_oak_chair",
    "valhelsia_furniture:black_upholstered_dark_oak_chair",
    "valhelsia_furniture:white_upholstered_mangrove_chair",
    "valhelsia_furniture:orange_upholstered_mangrove_chair",
    "valhelsia_furniture:magenta_upholstered_mangrove_chair",
    "valhelsia_furniture:light_blue_upholstered_mangrove_chair",
    "valhelsia_furniture:yellow_upholstered_mangrove_chair",
    "valhelsia_furniture:lime_upholstered_mangrove_chair",
    "valhelsia_furniture:pink_upholstered_mangrove_chair",
    "valhelsia_furniture:gray_upholstered_mangrove_chair",
    "valhelsia_furniture:light_gray_upholstered_mangrove_chair",
    "valhelsia_furniture:cyan_upholstered_mangrove_chair",
    "valhelsia_furniture:purple_upholstered_mangrove_chair",
    "valhelsia_furniture:blue_upholstered_mangrove_chair",
    "valhelsia_furniture:brown_upholstered_mangrove_chair",
    "valhelsia_furniture:green_upholstered_mangrove_chair",
    "valhelsia_furniture:red_upholstered_mangrove_chair",
    "valhelsia_furniture:black_upholstered_mangrove_chair",
    "valhelsia_furniture:white_upholstered_crimson_chair",
    "valhelsia_furniture:orange_upholstered_crimson_chair",
    "valhelsia_furniture:magenta_upholstered_crimson_chair",
    "valhelsia_furniture:light_blue_upholstered_crimson_chair",
    "valhelsia_furniture:yellow_upholstered_crimson_chair",
    "valhelsia_furniture:lime_upholstered_crimson_chair",
    "valhelsia_furniture:pink_upholstered_crimson_chair",
    "valhelsia_furniture:gray_upholstered_crimson_chair",
    "valhelsia_furniture:light_gray_upholstered_crimson_chair",
    "valhelsia_furniture:cyan_upholstered_crimson_chair",
    "valhelsia_furniture:purple_upholstered_crimson_chair",
    "valhelsia_furniture:blue_upholstered_crimson_chair",
    "valhelsia_furniture:brown_upholstered_crimson_chair",
    "valhelsia_furniture:green_upholstered_crimson_chair",
    "valhelsia_furniture:red_upholstered_crimson_chair",
    "valhelsia_furniture:black_upholstered_crimson_chair",
    "valhelsia_furniture:white_upholstered_warped_chair",
    "valhelsia_furniture:orange_upholstered_warped_chair",
    "valhelsia_furniture:magenta_upholstered_warped_chair",
    "valhelsia_furniture:light_blue_upholstered_warped_chair",
    "valhelsia_furniture:yellow_upholstered_warped_chair",
    "valhelsia_furniture:lime_upholstered_warped_chair",
    "valhelsia_furniture:pink_upholstered_warped_chair",
    "valhelsia_furniture:gray_upholstered_warped_chair",
    "valhelsia_furniture:light_gray_upholstered_warped_chair",
    "valhelsia_furniture:cyan_upholstered_warped_chair",
    "valhelsia_furniture:purple_upholstered_warped_chair",
    "valhelsia_furniture:blue_upholstered_warped_chair",
    "valhelsia_furniture:brown_upholstered_warped_chair",
    "valhelsia_furniture:green_upholstered_warped_chair",
    "valhelsia_furniture:red_upholstered_warped_chair",
    "valhelsia_furniture:black_upholstered_warped_chair",
  ],
  tables: [
    "valhelsia_furniture:oak_table",
    "valhelsia_furniture:spruce_table",
    "valhelsia_furniture:birch_table",
    "valhelsia_furniture:jungle_table",
    "valhelsia_furniture:acacia_table",
    "valhelsia_furniture:cherry_table",
    "valhelsia_furniture:dark_oak_table",
    "valhelsia_furniture:mangrove_table",
    "valhelsia_furniture:crimson_table",
    "valhelsia_furniture:warped_table",
    "valhelsia_furniture:white_oak_table",
    "valhelsia_furniture:orange_oak_table",
    "valhelsia_furniture:magenta_oak_table",
    "valhelsia_furniture:light_blue_oak_table",
    "valhelsia_furniture:yellow_oak_table",
    "valhelsia_furniture:lime_oak_table",
    "valhelsia_furniture:pink_oak_table",
    "valhelsia_furniture:gray_oak_table",
    "valhelsia_furniture:light_gray_oak_table",
    "valhelsia_furniture:cyan_oak_table",
    "valhelsia_furniture:purple_oak_table",
    "valhelsia_furniture:blue_oak_table",
    "valhelsia_furniture:brown_oak_table",
    "valhelsia_furniture:green_oak_table",
    "valhelsia_furniture:red_oak_table",
    "valhelsia_furniture:black_oak_table",
    "valhelsia_furniture:white_spruce_table",
    "valhelsia_furniture:orange_spruce_table",
    "valhelsia_furniture:magenta_spruce_table",
    "valhelsia_furniture:light_blue_spruce_table",
    "valhelsia_furniture:yellow_spruce_table",
    "valhelsia_furniture:lime_spruce_table",
    "valhelsia_furniture:pink_spruce_table",
    "valhelsia_furniture:gray_spruce_table",
    "valhelsia_furniture:light_gray_spruce_table",
    "valhelsia_furniture:cyan_spruce_table",
    "valhelsia_furniture:purple_spruce_table",
    "valhelsia_furniture:blue_spruce_table",
    "valhelsia_furniture:brown_spruce_table",
    "valhelsia_furniture:green_spruce_table",
    "valhelsia_furniture:red_spruce_table",
    "valhelsia_furniture:black_spruce_table",
    "valhelsia_furniture:white_birch_table",
    "valhelsia_furniture:orange_birch_table",
    "valhelsia_furniture:magenta_birch_table",
    "valhelsia_furniture:light_blue_birch_table",
    "valhelsia_furniture:yellow_birch_table",
    "valhelsia_furniture:lime_birch_table",
    "valhelsia_furniture:pink_birch_table",
    "valhelsia_furniture:gray_birch_table",
    "valhelsia_furniture:light_gray_birch_table",
    "valhelsia_furniture:cyan_birch_table",
    "valhelsia_furniture:purple_birch_table",
    "valhelsia_furniture:blue_birch_table",
    "valhelsia_furniture:brown_birch_table",
    "valhelsia_furniture:green_birch_table",
    "valhelsia_furniture:red_birch_table",
    "valhelsia_furniture:black_birch_table",
    "valhelsia_furniture:white_jungle_table",
    "valhelsia_furniture:orange_jungle_table",
    "valhelsia_furniture:magenta_jungle_table",
    "valhelsia_furniture:light_blue_jungle_table",
    "valhelsia_furniture:yellow_jungle_table",
    "valhelsia_furniture:lime_jungle_table",
    "valhelsia_furniture:pink_jungle_table",
    "valhelsia_furniture:gray_jungle_table",
    "valhelsia_furniture:light_gray_jungle_table",
    "valhelsia_furniture:cyan_jungle_table",
    "valhelsia_furniture:purple_jungle_table",
    "valhelsia_furniture:blue_jungle_table",
    "valhelsia_furniture:brown_jungle_table",
    "valhelsia_furniture:green_jungle_table",
    "valhelsia_furniture:red_jungle_table",
    "valhelsia_furniture:black_jungle_table",
    "valhelsia_furniture:white_acacia_table",
    "valhelsia_furniture:orange_acacia_table",
    "valhelsia_furniture:magenta_acacia_table",
    "valhelsia_furniture:light_blue_acacia_table",
    "valhelsia_furniture:yellow_acacia_table",
    "valhelsia_furniture:lime_acacia_table",
    "valhelsia_furniture:pink_acacia_table",
    "valhelsia_furniture:gray_acacia_table",
    "valhelsia_furniture:light_gray_acacia_table",
    "valhelsia_furniture:cyan_acacia_table",
    "valhelsia_furniture:purple_acacia_table",
    "valhelsia_furniture:blue_acacia_table",
    "valhelsia_furniture:brown_acacia_table",
    "valhelsia_furniture:green_acacia_table",
    "valhelsia_furniture:red_acacia_table",
    "valhelsia_furniture:black_acacia_table",
    "valhelsia_furniture:white_cherry_table",
    "valhelsia_furniture:orange_cherry_table",
    "valhelsia_furniture:magenta_cherry_table",
    "valhelsia_furniture:light_blue_cherry_table",
    "valhelsia_furniture:yellow_cherry_table",
    "valhelsia_furniture:lime_cherry_table",
    "valhelsia_furniture:pink_cherry_table",
    "valhelsia_furniture:gray_cherry_table",
    "valhelsia_furniture:light_gray_cherry_table",
    "valhelsia_furniture:cyan_cherry_table",
    "valhelsia_furniture:purple_cherry_table",
    "valhelsia_furniture:blue_cherry_table",
    "valhelsia_furniture:brown_cherry_table",
    "valhelsia_furniture:green_cherry_table",
    "valhelsia_furniture:red_cherry_table",
    "valhelsia_furniture:black_cherry_table",
    "valhelsia_furniture:white_dark_oak_table",
    "valhelsia_furniture:orange_dark_oak_table",
    "valhelsia_furniture:magenta_dark_oak_table",
    "valhelsia_furniture:light_blue_dark_oak_table",
    "valhelsia_furniture:yellow_dark_oak_table",
    "valhelsia_furniture:lime_dark_oak_table",
    "valhelsia_furniture:pink_dark_oak_table",
    "valhelsia_furniture:gray_dark_oak_table",
    "valhelsia_furniture:light_gray_dark_oak_table",
    "valhelsia_furniture:cyan_dark_oak_table",
    "valhelsia_furniture:purple_dark_oak_table",
    "valhelsia_furniture:blue_dark_oak_table",
    "valhelsia_furniture:brown_dark_oak_table",
    "valhelsia_furniture:green_dark_oak_table",
    "valhelsia_furniture:red_dark_oak_table",
    "valhelsia_furniture:black_dark_oak_table",
    "valhelsia_furniture:white_mangrove_table",
    "valhelsia_furniture:orange_mangrove_table",
    "valhelsia_furniture:magenta_mangrove_table",
    "valhelsia_furniture:light_blue_mangrove_table",
    "valhelsia_furniture:yellow_mangrove_table",
    "valhelsia_furniture:lime_mangrove_table",
    "valhelsia_furniture:pink_mangrove_table",
    "valhelsia_furniture:gray_mangrove_table",
    "valhelsia_furniture:light_gray_mangrove_table",
    "valhelsia_furniture:cyan_mangrove_table",
    "valhelsia_furniture:purple_mangrove_table",
    "valhelsia_furniture:blue_mangrove_table",
    "valhelsia_furniture:brown_mangrove_table",
    "valhelsia_furniture:green_mangrove_table",
    "valhelsia_furniture:red_mangrove_table",
    "valhelsia_furniture:black_mangrove_table",
    "valhelsia_furniture:white_crimson_table",
    "valhelsia_furniture:orange_crimson_table",
    "valhelsia_furniture:magenta_crimson_table",
    "valhelsia_furniture:light_blue_crimson_table",
    "valhelsia_furniture:yellow_crimson_table",
    "valhelsia_furniture:lime_crimson_table",
    "valhelsia_furniture:pink_crimson_table",
    "valhelsia_furniture:gray_crimson_table",
    "valhelsia_furniture:light_gray_crimson_table",
    "valhelsia_furniture:cyan_crimson_table",
    "valhelsia_furniture:purple_crimson_table",
    "valhelsia_furniture:blue_crimson_table",
    "valhelsia_furniture:brown_crimson_table",
    "valhelsia_furniture:green_crimson_table",
    "valhelsia_furniture:red_crimson_table",
    "valhelsia_furniture:black_crimson_table",
    "valhelsia_furniture:white_warped_table",
    "valhelsia_furniture:orange_warped_table",
    "valhelsia_furniture:magenta_warped_table",
    "valhelsia_furniture:light_blue_warped_table",
    "valhelsia_furniture:yellow_warped_table",
    "valhelsia_furniture:lime_warped_table",
    "valhelsia_furniture:pink_warped_table",
    "valhelsia_furniture:gray_warped_table",
    "valhelsia_furniture:light_gray_warped_table",
    "valhelsia_furniture:cyan_warped_table",
    "valhelsia_furniture:purple_warped_table",
    "valhelsia_furniture:blue_warped_table",
    "valhelsia_furniture:brown_warped_table",
    "valhelsia_furniture:green_warped_table",
    "valhelsia_furniture:red_warped_table",
    "valhelsia_furniture:black_warped_table",
  ],
  doors: [
    "minecraft:oak_door",
    "minecraft:spruce_door",
    "minecraft:birch_door",
    "minecraft:jungle_door",
    "minecraft:acacia_door",
    "minecraft:dark_oak_door",
    "minecraft:iron_door",
    "regions_unexplored:alpha_door",
    "regions_unexplored:baobab_door",
    "regions_unexplored:blackwood_door",
    "regions_unexplored:blue_bioshroom_door",
    "regions_unexplored:cobalt_door",
    "regions_unexplored:cypress_door",
    "regions_unexplored:dead_door",
    "regions_unexplored:eucalyptus_door",
    "regions_unexplored:green_bioshroom_door",
    "regions_unexplored:jacaranda_door",
    "regions_unexplored:larch_door",
    "regions_unexplored:magnolia_door",
    "regions_unexplored:maple_door",
    "regions_unexplored:mahogany_door",
    "regions_unexplored:palm_door",
    "regions_unexplored:pine_door",
    "regions_unexplored:redwood_door",
    "regions_unexplored:willow_door",
    "regions_unexplored:white_bioshroom_door",
    "regions_unexplored:yellow_bioshroom_door",
    "quark:acacia_blossom_door",
    "quark:blossom_door",
    "quark:dark_oak_blossom_door",
    "quark:oak_blossom_door",
    "quark:spruce_blossom_door",
    "regions_unexplored:alpha_door",
    "regions_unexplored:baobab_door",
    "regions_unexplored:blackwood_door",
    "regions_unexplored:blue_bioshroom_door",
    "regions_unexplored:cobalt_door",
    "regions_unexplored:cypress_door",
    "regions_unexplored:dead_door",
    "regions_unexplored:eucalyptus_door",
    "regions_unexplored:green_bioshroom_door",
    "regions_unexplored:jacaranda_door",
    "regions_unexplored:larch_door",
    "regions_unexplored:magnolia_door",
    "regions_unexplored:maple_door",
    "regions_unexplored:mahogany_door",
    "regions_unexplored:palm_door",
    "regions_unexplored:pine_door",
    "regions_unexplored:redwood_door",
    "regions_unexplored:willow_door",
    "regions_unexplored:white_bioshroom_door",
    "regions_unexplored:yellow_bioshroom_door",
    "mcwdoors:acacia_barn_door",
    "mcwdoors:acacia_double_door",
    "mcwdoors:acacia_four_panel_door",
    "mcwdoors:acacia_glass_door",
    "mcwdoors:acacia_modern_door",
    "mcwdoors:acacia_mystic_door",
    "mcwdoors:acacia_paper_door",
    "mcwdoors:acacia_school_door",
    "mcwdoors:acacia_stable_door",
    "mcwdoors:acacia_tall_door",
    "mcwdoors:acacia_two_panel_door",
    "mcwdoors:birch_barn_door",
    "mcwdoors:birch_double_door",
    "mcwdoors:birch_four_panel_door",
    "mcwdoors:birch_glass_door",
    "mcwdoors:birch_modern_door",
    "mcwdoors:birch_mystic_door",
    "mcwdoors:birch_paper_door",
    "mcwdoors:birch_school_door",
    "mcwdoors:birch_stable_door",
    "mcwdoors:birch_tall_door",
    "mcwdoors:birch_two_panel_door",
    "mcwdoors:crimson_barn_door",
    "mcwdoors:crimson_double_door",
    "mcwdoors:crimson_four_panel_door",
    "mcwdoors:crimson_glass_door",
    "mcwdoors:crimson_modern_door",
    "mcwdoors:crimson_mystic_door",
    "mcwdoors:crimson_paper_door",
    "mcwdoors:crimson_school_door",
    "mcwdoors:crimson_stable_door",
    "mcwdoors:crimson_tall_door",
    "mcwdoors:crimson_two_panel_door",
    "mcwdoors:dark_oak_barn_door",
    "mcwdoors:dark_oak_double_door",
    "mcwdoors:dark_oak_four_panel_door",
    "mcwdoors:dark_oak_glass_door",
    "mcwdoors:dark_oak_modern_door",
    "mcwdoors:dark_oak_mystic_door",
    "mcwdoors:dark_oak_paper_door",
    "mcwdoors:dark_oak_school_door",
    "mcwdoors:dark_oak_stable_door",
    "mcwdoors:dark_oak_tall_door",
    "mcwdoors:dark_oak_two_panel_door",
    "mcwdoors:jungle_barn_door",
    "mcwdoors:jungle_double_door",
    "mcwdoors:jungle_four_panel_door",
    "mcwdoors:jungle_glass_door",
    "mcwdoors:jungle_modern_door",
    "mcwdoors:jungle_mystic_door",
    "mcwdoors:jungle_paper_door",
    "mcwdoors:jungle_school_door",
    "mcwdoors:jungle_stable_door",
    "mcwdoors:jungle_tall_door",
    "mcwdoors:jungle_two_panel_door",
    "mcwdoors:oak_barn_door",
    "mcwdoors:oak_double_door",
    "mcwdoors:oak_four_panel_door",
    "mcwdoors:oak_glass_door",
    "mcwdoors:oak_modern_door",
    "mcwdoors:oak_mystic_door",
    "mcwdoors:oak_paper_door",
    "mcwdoors:oak_school_door",
    "mcwdoors:oak_stable_door",
    "mcwdoors:oak_tall_door",
    "mcwdoors:oak_two_panel_door",
    "mcwdoors:spruce_barn_door",
    "mcwdoors:spruce_double_door",
    "mcwdoors:spruce_four_panel_door",
    "mcwdoors:spruce_glass_door",
    "mcwdoors:spruce_modern_door",
    "mcwdoors:spruce_mystic_door",
    "mcwdoors:spruce_paper_door",
    "mcwdoors:spruce_school_door",
    "mcwdoors:spruce_stable_door",
    "mcwdoors:spruce_tall_door",
    "mcwdoors:spruce_two_panel_door",
    "mcwdoors:warped_barn_door",
    "mcwdoors:warped_double_door",
    "mcwdoors:warped_four_panel_door",
    "mcwdoors:warped_glass_door",
    "mcwdoors:warped_modern_door",
    "mcwdoors:warped_mystic_door",
    "mcwdoors:warped_paper_door",
    "mcwdoors:warped_school_door",
    "mcwdoors:warped_stable_door",
    "mcwdoors:warped_tall_door",
    "mcwdoors:warped_two_panel_door",
  ],
  light: [
    "minecraft:torch",
    "minecraft:lantern",
    "decorative_blocks:soul_chandelier",
    "decorative_blocks:chandelier",
    "luminous_nether:ghost_lantern",
    "quark:paper_lantern",
    "quark:paper_lantern_sakura",
    "aether_redux:sentrite_lantern",
    "minecraft:jack_o_lantern",
    "minecraft:sea_lantern",
    "aether:ambrosium_torch",
  ],
};

let npcRequirements = {
  "minecraft:crafting_table": ["chairs", "tables", "doors", "light"],
  "drinkbeer:bartending_table_normal": ["chairs", "tables", "doors", "light"],
  "doggytalents:dog_bed": ["chairs", "tables", "doors", "light"],
  "irons_spellbooks:alchemist_cauldron": ["chairs", "tables", "doors", "light"],
  "minecraft:red_bed": ["chairs", "tables", "doors", "light"],
  "numismatic-overhaul:shop": ["chairs", "tables", "doors", "light"],
  "cataclysm:mechanical_fusion_anvil": ["chairs", "tables", "doors", "light"],
  "minecraft:flower_pot": ["chairs", "tables", "doors", "light"],
  "quark:gunpowder_sack": ["chairs", "tables", "doors", "light"],
  "aquaculture:tackle_box": ["chairs", "tables", "doors", "light"],
  "sophisticatedstorage:decoration_table": [
    "chairs",
    "tables",
    "doors",
    "light",
  ],
};

BlockEvents.placed((event) => {
  let block = event.block;
  let player = event.player;
  let level = event.level;
  let pos = block.pos;

  if (!(block.id in NPC_COMMANDS)) return;

  activeNpcBlocks.add(`${pos.x},${pos.y},${pos.z}`);

  let searchRadius = 10;
  let foundConditions = {};

  let requiredCategories = npcRequirements[block.id] || [];
  requiredCategories.forEach((category) => {
    foundConditions[category] = false;
  });

  for (let x = -searchRadius; x <= searchRadius; x++) {
    for (let y = -searchRadius; y <= searchRadius; y++) {
      for (let z = -searchRadius; z <= searchRadius; z++) {
        let nearbyPos = pos.offset(x, y, z);
        let nearbyBlock = level.getBlock(nearbyPos);

        for (let category of requiredCategories) {
          if (categoryBlocks[category].includes(nearbyBlock.id)) {
            foundConditions[category] = true;
          }
        }

        if (Object.values(foundConditions).every(Boolean)) break;
      }
      if (Object.values(foundConditions).every(Boolean)) break;
    }
    if (Object.values(foundConditions).every(Boolean)) break;
  }

  if (Object.values(foundConditions).every(Boolean)) {
    let command = NPC_COMMANDS[block.id].replace(
      "~ ~ ~",
      `${pos.x} ${pos.y} ${pos.z}`
    );
    player.server.runCommand(command);

    if (block.id in NPC_HOME_COMMANDS) {
      let homeCommand = NPC_HOME_COMMANDS[block.id].replace(
        "~ ~ ~",
        `${pos.x} ${pos.y} ${pos.z}`
      );
      let questCommand = NPC_QUEST_COMMANDS[block.id];
      player.server.runCommand(homeCommand);
      player.server.runCommand(questCommand);
      player.tell("This housing is suitable.");
    }
  }
});

BlockEvents.broken((event) => {
  let block = event.block;
  let pos = block.pos;

  if (npcSpawnBlocks.includes(block.id)) {
    activeNpcBlocks.delete(`${pos.x},${pos.y},${pos.z}`);
  }
});
