#In order for the block to be found by the Metal Detector
#You need to fill the list with string like 'modid:block[state1=true]' or 'modid:block'
#The order of the blocks in the list is the order of their rarity
rareBlocks = ["stalwart_dungeons:tungsten_ore", "prodigium:orichalcum_ore", "prodigium:palladium_ore", "prodigium:deepslate_palladium_ore", "simpleores:onyx_ore", "simpleores:adamantium_ore", "simpleores:deepslate_adamantium_ore", "minecraft:ancient_debris", "minecraft:suspicious_gravel", "minecraft:suspicious_sand", "minecraft:deepslate_emerald_ore", "minecraft:emerald_ore", "minecraft:deepslate_diamond_ore", "minecraft:diamond_ore", "minecraft:deepslate_lapis_ore", "minecraft:lapis_ore", "minecraft:nether_gold_ore", "minecraft:deepslate_gold_ore", "minecraft:gold_ore", "minecraft:nether_quartz_ore"]
#In order for the creature to be found by the Life Form Analyzer
#You need to fill the list with string like 'modid:entity'
#The order of the entities in the list is the order of their rarity
rareCreatures = ["minecraft:panda", "minecraft:skeleton_horse", "minecraft:allay", "minecraft:axolotl", "minecraft:evoker", "minecraft:piglin_prute", "minecraft:vindicator", "minecraft:enderman"]
#Range: 6 ~ 100
"Max Accessory Amount" = 7

["Random Attack Damage"]
	enable = true
	#Range: 0.0 ~ 1.0
	min = 0.8
	#Range: 1.0 ~ 2.0
	max = 1.2

["Invulnerable Time"]
	#Range: > 0
	CrossNecklace = 15
	#Range: > 0
	StarVeil = 20

["Fall Resistance"]
	#Range: > -1
	AmberHorseshoeBalloon = -1
	#Range: > -1
	AmbhipianBoots = 7
	#Range: > -1
	BlueHorseshoeBalloon = -1
	#Range: > -1
	BundleOfHorseshoeBalloons = -1
	#Range: > -1
	FrogFlipper = 7
	#Range: > -1
	FrogLeg = 7
	#Range: > -1
	GreenHorseshoeBalloon = -1
	#Range: > -1
	LuckyHorseshoe = -1
	#Range: > -1
	ObsidianHorseshoe = -1
	#Range: > -1
	PinkHorseshoeBalloon = -1
	#Range: > -1
	WhiteHorseshoeBalloon = -1
	#Range: > -1
	YellowHorseshoeBalloon = -1

["Jump Boost"]
	#Range: 0.0 ~ 1.7976931348623157E308
	AmberHorseshoeBalloon = 1.75
	#Range: 0.0 ~ 1.7976931348623157E308
	AmbhipianBoots = 1.6
	#Range: 0.0 ~ 1.7976931348623157E308
	Balloon = 1.33
	#Range: 0.0 ~ 1.7976931348623157E308
	BlizzardInABalloon = 1.33
	#Range: 0.0 ~ 1.7976931348623157E308
	BlueHorseshoeBalloon = 1.75
	#Range: 0.0 ~ 1.7976931348623157E308
	BundleOfBalloons = 1.33
	#Range: 0.0 ~ 1.7976931348623157E308
	BundleOfHorseshoeBalloons = 1.33
	#Range: 0.0 ~ 1.7976931348623157E308
	CloudInABalloon = 1.33
	#Range: 0.0 ~ 1.7976931348623157E308
	FartInABalloon = 1.33
	#Range: 0.0 ~ 1.7976931348623157E308
	FrogFlipper = 1.6
	#Range: 0.0 ~ 1.7976931348623157E308
	FrogLeg = 1.6
	#Range: 0.0 ~ 1.7976931348623157E308
	GreenHorseshoeBalloon = 1.33
	#Range: 0.0 ~ 1.7976931348623157E308
	HoneyBalloon = 1.33
	#Range: 0.0 ~ 1.7976931348623157E308
	PinkHorseshoeBalloon = 1.33
	#Range: 0.0 ~ 1.7976931348623157E308
	SandstormInABalloon = 1.33
	#Range: 0.0 ~ 1.7976931348623157E308
	SharkronBalloon = 1.33
	#Range: 0.0 ~ 1.7976931348623157E308
	WhiteHorseshoeBalloon = 1.33
	#Range: 0.0 ~ 1.7976931348623157E308
	YellowHorseshoeBalloon = 1.75

["May Fly"]

	["May Fly"."Fly Ticks"]
		#Range: > 0
		FairyBoots = 32
		#Range: > 0
		FrostsparkBoots = 32
		#Range: > 0
		LightningBoots = 32
		#Range: > 0
		RocketBoots = 32
		#Range: > 0
		SpectreBoots = 32
		#Range: > 0
		TerrasparkBoots = 42

	["May Fly"."Fly Speed"]
		#Range: 0.0 ~ 1.7976931348623157E308
		FairyBoots = 0.3
		#Range: 0.0 ~ 1.7976931348623157E308
		FrostsparkBoots = 0.3
		#Range: 0.0 ~ 1.7976931348623157E308
		LightningBoots = 0.3
		#Range: 0.0 ~ 1.7976931348623157E308
		RocketBoots = 0.3
		#Range: 0.0 ~ 1.7976931348623157E308
		SpectreBoots = 0.3
		#Range: 0.0 ~ 1.7976931348623157E308
		TerrasparkBoots = 0.35

["Multi Jump"]

	["Multi Jump"."Jump Ticks"]
		#Range: > 0
		BlizzardInABalloon = 16
		#Range: > 0
		BlizzardInABottle = 16
		#Range: > 0
		SandstormInABalloon = 20
		#Range: > 0
		SandstormInABottle = 20

	["Multi Jump"."Jump Speed"]
		#Range: 0.0 ~ 1.7976931348623157E308
		BlizzardInABalloon = 0.4
		#Range: 0.0 ~ 1.7976931348623157E308
		BlizzardInABottle = 0.4
		#Range: 0.0 ~ 1.7976931348623157E308
		CloudInABalloon = 1.1
		#Range: 0.0 ~ 1.7976931348623157E308
		CloudInABottle = 1.1
		#Range: 0.0 ~ 1.7976931348623157E308
		FartInABalloon = 2.1
		#Range: 0.0 ~ 1.7976931348623157E308
		FartInAJar = 2.8
		#Range: 0.0 ~ 1.7976931348623157E308
		SandstormInABalloon = 0.45
		#Range: 0.0 ~ 1.7976931348623157E308
		SandstormInABottle = 0.45
		#Range: 0.0 ~ 1.7976931348623157E308
		SharkronBalloon = 1.1
		#Range: 0.0 ~ 1.7976931348623157E308
		TsunamiInABottle = 1.0

["Magic Quiver"]
	#Range: 0.0 ~ 1.0
	arrowNoConsumeChance = 0.25

[Attributes]

	[Attributes."Ankh Shield"]
		#Range: 0.0 ~ 1.0
		knockbackResistance = 1.0
		#Range: 0 ~ 1024
		armor = 4

	[Attributes."Avenger Emblem"]
		#Range: 0.0 ~ 10.0
		attackDamage = 0.12
		#Range: 0.0 ~ 10.0
		rangedDamage = 0.12
		#Range: 0.0 ~ 10.0
		magicDamage = 0.12

	[Attributes."Berserker's Glove"]
		#Range: 0 ~ 1024
		armor = 8
		#Range: 0.0 ~ 10.0
		attackSpeed = 0.12
		#Range: 0.0 ~ 1.0
		attackKnockback = 1.0
		#Range: 0.0 ~ 1024.0
		entityReach = 0.1
		#Range: -10000 ~ 10000
		aggro = 400

	[Attributes."Celestial Stone"]
		#Range: 0.0 ~ 10.0
		attackSpeed = 0.1
		#Range: 0.0 ~ 10.0
		attackDamage = 0.1
		#Range: 0 ~ 1024
		armor = 4
		#Range: 0.0 ~ 1.0
		criticalChance = 0.02
		#Range: 0.0 ~ 10.0
		miningSpeed = 0.15
		#Range: 0.0 ~ 10.0
		rangedDamage = 0.1
		#Range: 0.0 ~ 10.0
		magicDamage = 0.1

	[Attributes."Cobalt Shield"]
		#Range: 0.0 ~ 1.0
		knockbackResistance = 1.0
		#Range: 0 ~ 1024
		armor = 1

	[Attributes."Destroyer Emblem"]
		#Range: 0.0 ~ 10.0
		attackDamage = 0.1
		#Range: 0.0 ~ 1.0
		criticalChance = 0.08
		#Range: 0.0 ~ 10.0
		rangedDamage = 0.1
		#Range: 0.0 ~ 10.0
		magicDamage = 0.1

	[Attributes."Feral Claws"]
		#Range: 0.0 ~ 10.0
		attackSpeed = 0.12

	[Attributes."Fire Gauntlet"]
		#Range: 0.0 ~ 10.0
		attackDamage = 0.12
		#Range: 0.0 ~ 10.0
		attackSpeed = 0.12
		#Range: 0.0 ~ 1.0
		attackKnockback = 1.0
		#Range: 0.0 ~ 1024.0
		entityReach = 0.1

	[Attributes."Flesh Knuckles"]
		#Range: 0 ~ 1024
		armor = 8
		#Range: -10000 ~ 10000
		aggro = 400

	[Attributes."Frozen Shield"]
		#Range: 0 ~ 1024
		armor = 6
		#Range: 0.0 ~ 1.0
		knockbackResistance = 1.0

	[Attributes."Hero Shield"]
		#Range: 0 ~ 1024
		armor = 10
		#Range: 0.0 ~ 1.0
		knockbackResistance = 1.0
		#Range: -10000 ~ 10000
		aggro = 400

	[Attributes."Mechanical Glove"]
		#Range: 0.0 ~ 10.0
		attackDamage = 0.12
		#Range: 0.0 ~ 1.0
		attackKnockback = 1.0
		#Range: 0.0 ~ 1024.0
		entityReach = 0.1

	[Attributes."Moon Stone"]
		#Range: 0.0 ~ 10.0
		attackSpeed = 0.1
		#Range: 0.0 ~ 10.0
		attackDamage = 0.1
		#Range: 0 ~ 1024
		armor = 4
		#Range: 0.0 ~ 1.0
		criticalChance = 0.02
		#Range: 0.0 ~ 10.0
		miningSpeed = 0.15
		#Range: 0.0 ~ 10.0
		rangedDamage = 0.1
		#Range: 0.0 ~ 10.0
		magicDamage = 0.1

	[Attributes."Obsidian Shield"]
		#Range: 0.0 ~ 1.0
		knockbackResistance = 1.0
		#Range: 0 ~ 1024
		armor = 2

	[Attributes."Paladins Shield"]
		#Range: 0 ~ 1024
		armor = 7
		#Range: 0.0 ~ 1.0
		knockbackResistance = 1.0

	[Attributes."Panic Necklace"]
		#Range: 0.0 ~ 10.0
		movementSpeed = 1.0

	[Attributes."Power Glove"]
		#Range: 0.0 ~ 10.0
		attackSpeed = 0.12
		#Range: 0.0 ~ 10.0
		attackKnockback = 1.0
		#Range: 0.0 ~ 1024.0
		entityReach = 0.1

	[Attributes."Putrid Scent"]
		#Range: 0.0 ~ 10.0
		attackDamage = 0.05
		#Range: 0.0 ~ 1.0
		criticalChance = 0.05
		#Range: -10000 ~ 10000
		aggro = -400

	[Attributes.Shackle]
		#Range: 0 ~ 1024
		armor = 1

	[Attributes."Sun Stone"]
		#Range: 0.0 ~ 10.0
		attackSpeed = 0.1
		#Range: 0.0 ~ 10.0
		attackDamage = 0.1
		#Range: 0 ~ 1024
		armor = 4
		#Range: 0.0 ~ 1.0
		criticalChance = 0.02
		#Range: 0.0 ~ 10.0
		miningSpeed = 0.15
		#Range: 0.0 ~ 10.0
		rangedDamage = 0.1
		#Range: 0.0 ~ 10.0
		magicDamage = 0.1

	[Attributes."Titan Glove"]
		#Range: 0.0 ~ 10.0
		attackKnockback = 1.0
		#Range: 0.0 ~ 1024.0
		entityReach = 0.1

	[Attributes."Warrior Emblem"]
		#Range: 0.0 ~ 10.0
		attackDamage = 0.15

	[Attributes."Extendo Grip"]
		#Range: 0.0 ~ 1024.0
		blockReach = 3.0

	[Attributes.Toolbelt]
		#Range: 0.0 ~ 1024.0
		blockReach = 1.0

	[Attributes.Toolbox]
		#Range: 0.0 ~ 1024.0
		blockReach = 1.0

	[Attributes."Shield Of Cthulhu"]
		#Range: 0 ~ 1024
		armor = 2
		#Range: 0.0 ~ 1.0
		criticalChance = 0.04

	[Attributes."Angler Earring"]
		#Range: -1024.0 ~ 1024.0
		luck = 10.0

	[Attributes.Aglet]
		#Range: 0.0 ~ 10.0
		movementSpeed = 0.05

	[Attributes."Anklet of the Wind"]
		#Range: 0.0 ~ 10.0
		movementSpeed = 0.1

	[Attributes.Flipper]
		#Range: 0.0 ~ 10.0
		swimSpeed = 0.5

	[Attributes."Lucky Horseshoe"]
		#Range: -1024.0 ~ 1024.0
		luck = 0.05

	[Attributes.Magiluminescence]
		#Range: 0.0 ~ 10.0
		movementSpeed = 0.15

	[Attributes.EyeOfTheGolem]
		#Range: 0.0 ~ 1.0
		criticalChance = 0.1

	[Attributes."Recon Scope"]
		#Range: 0.0 ~ 1.0
		criticalChance = 0.1
		#Range: 0.0 ~ 10.0
		rangedDamage = 0.1
		#Range: -10000 ~ 10000
		aggro = -400

	[Attributes."Sniper Scope"]
		#Range: 0.0 ~ 1.0
		criticalChance = 0.1
		#Range: 0.0 ~ 10.0
		rangedDamage = 0.1

	[Attributes."Ancient Chisel"]
		#Range: 0.0 ~ 10.0
		miningSpeed = 0.25

	[Attributes."Hand Of Creation"]
		#Range: 0.0 ~ 1024.0
		blockReach = 3.0
		#Range: 0.0 ~ 10.0
		miningSpeed = 0.25

	[Attributes."Magic Quiver"]
		#Range: 0.0 ~ 10.0
		rangedDamage = 0.1
		#Range: 0.0 ~ 10.0
		rangedVelocity = 0.2

	[Attributes."Molten Quiver"]
		#Range: 0.0 ~ 10.0
		rangedDamage = 0.1
		#Range: 0.0 ~ 10.0
		rangedVelocity = 0.2

	[Attributes."Ranger Emblem"]
		#Range: 0.0 ~ 10.0
		rangedDamage = 0.15

	[Attributes."Shark Tooth Necklace"]
		#Range: 0 ~ 10000
		armorPass = 5

	[Attributes."Sorcerer Emblem"]
		#Range: 0.0 ~ 10.0
		magicDamage = 0.15

	[Attributes."Stalker Quiver"]
		#Range: 0.0 ~ 10.0
		rangedDamage = 0.1
		#Range: 0.0 ~ 10.0
		rangedVelocity = 0.2
		#Range: -10000 ~ 10000
		aggro = -400

	[Attributes."Stinger Necklace"]
		#Range: 0 ~ 10000
		armorPass = 5

	[Attributes."Treasure Magnet"]
		#Range: 0.0 ~ 64.0
		pickupRange = 6.25

