
[bosses]
	#The minimum health a boss can have after applying the damage cap.
	MIN_HEALTH = 200.0
	#The divisor used to calculate the damage cap.
	DIVISION = 20.0
	#A list of entity IDs that should be excluded from the damage cap.
	#Example: ["minecraft:warden", "minecraft:ender_dragon"]
	BLACKLIST = ["minecraft:player"]

