
#General configuration settings
[General]
	#Use F3+H to show tooltips and get the name of the item, place it here. It get delete. Example: ["minecraft:stone"]
	#or if you need to ban multiple ["minecraft:stone", "minecraft:dirt"]
	"Items To Delete" = ["scalinghealth:heart_crystal", "scalinghealth:heart_crystal_shard", "scalinghealth:heart_dust", "scalinghealth:power_crystal", "scalinghealth:power_crystal_shard", "scalinghealth:cursed_heart", "scalinghealth:enchanted_heart", "scalinghealth:bandages", "scalinghealth:medkit", "simpleores:onyx_bow", "simpleores:mythril_bow", "somebosses:rusty_sword_relic", "scalinghealth:chance_heart"]
	#Enables/Disables the constant removal of items.
	"Is it on?" = true

