#If boss health should be scaled
"Should Scale Boss Health" = true
#If boss drops should be rolled an additional time per player
"Should Scale Boss Drops" = true
#The amount to scale boss health per player after the first
#Range: 0.0 ~ 1.7976931348623157E308
"Health Multiplier Per Player" = 0.3
#A flat value to increase boss health. Will override "Health Multiplier Per Player" if it is not 0
#Range: 0.0 ~ 1.7976931348623157E308
"Flat Health Multiplier" = 0.0
#A flat value to increase boss. If this value is not 0 player count will be ignored
#Range: > 0
"Flat Drop Multiplier" = 0
#Whether to use the forge tag "forge:bosses" to detect bosses
"Should Use Forge Tags" = true
#A list of items to log on common setup.
bossEntities = ["aether:valkyrie_queen", "aether:sun_spirit", "terrawhips_and_more:thekingslime", "aether:slider", "bosses_of_mass_destruction:void_blossom", "bosses_of_mass_destruction:gauntlet", "bosses_of_mass_destruction:lich", "bosses_of_mass_destruction:obsidilith", "minecraft:wither", "minecraft:ender_dragon", "conjurer_illager:conjurer", "minecraft:elder_guardian", "stalwart_dungeons:nether_keeper", "stalwart_dungeons:awful_ghast", "cataclysm:netherite_monstrosity", "cataclysm:ignis", "minecraft:warden", "cataclysm:the_harbinger", "alexsmobs:void_worm", "stalwart_dungeons:shelterer", "cataclysm:ender_guardian", "cataclysm:ender_golem", "cataclysm:ancient_remnant", "irons_spellbooks:dead_king", "cataclysm:the_leviathan", "mowziesmobs:umvuthi", "mowziesmobs:frostmaw"]

