#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Jun 13 17:44:13 CEST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=12
shaderPack=ComplementaryReimagined_r5.6.1.zip
enableShaders=false
