#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri May 01 23:45:02 CEST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=12
shaderPack=ComplementaryReimagined_r5.6.1.zip
enableShaders=false
