
[client]
	#Boss Bar Style.
	#0: Default, 1: Still Style, 2: Dynamic Style
	#Range: 0 ~ 2
	boss_bar_style = 2
	#Boss Bar Number Offset X.
	#Range: -150 ~ 300
	boss_bar_number_offset_x = 0
	#Boss Bar Number Offset Y.
	#Range: -100 ~ 200
	boss_bar_number_offset_y = 0
	#Generate Whip Particle.
	generate_whip_particle = true
	enableNonSpiderModel = false

[server]
	#When a boss has no target, should it be cleared?
	boss_clear_when_no_target = false
	#Multiplier for boss attributes health.
	#Range: 0.0625 ~ 10.0
	boss_attributes_multiplier_health = 0.35
	#Multiplier for boss attributes damage.
	#Range: 0.0625 ~ 10.0
	boss_attributes_multiplier_damage = 0.15
	#Should the boss have no physics? Only for some bosses.
	boss_no_physics = true
	#Should the boss leave on day? Only for some bosses.
	boss_leave_on_day = false
	#Should summon items be displayed in this mod?
	display_summon_items = true
	#Should all monsters be enhanced?
	#If false, only specific monsters in this mod.
	enhance_all_monster = false
	#Multiplier for monster attributes health.
	#Range: 0.0625 ~ 100.0
	monster_attributes_multiplier_health = 1.0
	#Multiplier for monster attributes damage.
	#Range: 0.0625 ~ 100.0
	monster_attributes_multiplier_damage = 1.0

