
[wormhole-artifact-config]
	#Max durability for the wormhole artifact
	#Range: 1 ~ 99999
	wormhole_artifact_max_durability = 16
	#Max durability for the wormhole artifact
	#Range: 1 ~ 99999
	wormhole_remote_max_durability = 64
	#Time in seconds for the wormhole artifact cooldown
	#Range: 0 ~ 99999
	wormhole_artifact_cooldown = 5
	#Time in seconds for the wormhole remote cooldown
	#Range: 0 ~ 99999
	wormhole_remote_cooldown = 2
	#Probability from 0 to 1 (1 for 100%) from Ender Pearl to drop an Ender Nacre when teleported (0 for deactivate)
	#Range: 0.0 ~ 1.0
	ender_nacre_drop_probability = 0.5

