#Optional Compatibility Modules
#Sun Sep 13 13:44:53 CEST 2026
irons_spellbooks.resolver_summons=true
irons_spellbooks.element_castbar=true
irons_spellbooks.element_manabar_is=true
irons_spellbooks.hostile_spell_registry=true
