#How often should Fixed Invasions occur.
#Range: > 1
fixedInvasionRarity = 8
#Determines if fixed invasions can be canceled.
cancelableFixedInvasions = true
#How often should fixed invasions be canceled.
#NOTE: An invasion is canceled once in every 'value' fixed invasions.
#NOTE: If an invasion is set to be cancel on the same cycle as a hyper/nightmare invasion, it will not be cancled.
#Range: > 1
fixedCancelInvasionRarity = 32
#Max Fixed Invasions that can occur at once.
#Range: > 1
maxFixedInvasions = 3
#How many days should pass when the Fixed Invasion Tier increases.
#Range: > 1
fixedTierIncreaseDelay = 40
#How often should Hyper Invasions occur.
#Range: > 1
hyperInvasionRarity = 10
#How often should Nightmare Invasions occur.
#Range: > 1
nightmareInvasionRarity = 4

